name: Build FantasyNameGenerator

on:
  push:
    branches: [ "master", "task/create_workflow" ]
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches-ignore: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      Wpf_App: FantasyNameGenerator.WPF\FantasyNameGenerator.WPF.csproj
      Configuration: ${{ matrix.configuration }}
      Runtime: win-x64
      Output_Dir: publish
      Zip_Filename: FantasyNameGenerator_${{ matrix.configuration }}.zip

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration ${{ env.Configuration }} --no-restore

    - name: Execute unit tests
      if: matrix.configuration == 'Debug'
      run: dotnet test --configuration ${{ env.Configuration }} --no-build

    - name: Publish app
      if: matrix.configuration == 'Release'
      run: >
        dotnet publish ${{ env.Wpf_App }}
        -c ${{ env.Configuration }}
        -r ${{ env.Runtime }}
        --self-contained true
        -p:PublishSingleFile=true
        -o ${{ env.Output_Dir }}

    - name: Create ZIP archive
      if: matrix.configuration == 'Release'
      run: Compress-Archive -Path ${{ env.Output_Dir }}\* -DestinationPath ${{ env.Zip_Filename }}

    - name: Upload artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: FantasyNameGenerator
        path: ${{ env.Zip_Filename }}

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download ZIP from build job
      uses: actions/download-artifact@v4
      with:
        name: FantasyNameGenerator
    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Fantasy Name Generator ${{ github.ref_name }}
        body: |
          New release for FantasyNameGenerator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload ZIP to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: FantasyNameGenerator.zip
        asset_name: FantasyNameGenerator.zip
        asset_content_type: application/zip